import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./default/Footer";
import Header from "./default/Header";
import StyledComponentsRegistry from "./registry";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "모강: 당신을 위한 모든 강의",
  description: "Generated by withPodo",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>

      <body
        className={inter.className}
        style={{
          padding: "0px",
          margin: "0px",
        }}
      >
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
